version: '2'
services:
  web:
    image: jahia-web
    hostname: Jahia-CMS
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db:db

  db:
    image: jahia-db
    hostname: Jahia-DB
    environment:
      - CREATEDB=true
      - MYSQL_CLIENT=%
      - MYSQL_PASS=root
      - MYSQL_DB=digital_factory
      - APP_USER=jahia
      - APP_PASS=jahia
